# Numpy Tutorial

## Introducing Numpy Arrays

###### 0.import numpy library

In [2]:
import numpy as np

###### 1.Simple array creation

In [3]:
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

###### checking the type of array

In [4]:
type(a)

numpy.ndarray

###### numeric type of elements:

In [5]:
a.dtype

dtype('int32')

###### number of dimensions:

In [6]:
a.ndim

1

###### Array shape

In [7]:
a.shape

(4,)

###### Bytes per element

In [8]:
a.itemsize

4

###### Bytes of memeory used

In [9]:
a.nbytes

16

# Array Operations

## simple array math

In [10]:
a=np.array([0,1,2,3])
b=np.array([4,5,6,7])
a+b

array([ 4,  6,  8, 10])

In [11]:
a*b

array([ 0,  5, 12, 21])

In [12]:
a-b

array([-4, -4, -4, -4])

In [13]:
a**b

array([   0,    1,   64, 2187], dtype=int32)

## Math functions

In [14]:
a=np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
b=np.pi/10
b

0.3141592653589793

In [16]:
b*a

array([0.        , 0.31415927, 0.62831853, 0.9424778 , 1.25663706,
       1.57079633, 1.88495559, 2.19911486, 2.51327412, 2.82743339,
       3.14159265])

In [17]:
y=np.sin(a)
y

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

# setting array elements

In [18]:
a[0]

0

In [19]:
a[0]=10
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
#beware of type coercoin
a[0]=10.6
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
a.fill(-5.6)
a

array([-5, -5, -5, -5, -5, -5, -5, -5, -5, -5, -5])

# Multidimensional Array

In [22]:
a=np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
a.shape

(2, 4)

In [24]:
a.size

8

In [25]:
a.ndim

2

In [26]:
a[1,3]=13
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 13]])

In [27]:
a[1]

array([ 4,  5,  6, 13])

In [28]:
a[1][1]

5

# Indexing and Slicing

## 1.Slicing:var[lower:upper:step]

In [29]:
a=np.array([10,11,12,13])
a

array([10, 11, 12, 13])

In [30]:
a[1:3]

array([11, 12])

In [31]:
a[1:-2]

array([11])

## omitting indices:

In [32]:
a[:3]

array([10, 11, 12])

In [33]:
a[-2:]

array([12, 13])

###### every other element:

In [34]:
a[::2]

array([10, 12])

In [35]:
a

array([10, 11, 12, 13])

In [36]:
a=np.array([[1,2,3,4,5,6],[6,7,8,9,0,4],[5,4,6,8,7,5],[5,4,1,2,3,5],[4,2,4,6,5,7],[10,5,2,56,45,56]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9,  0,  4],
       [ 5,  4,  6,  8,  7,  5],
       [ 5,  4,  1,  2,  3,  5],
       [ 4,  2,  4,  6,  5,  7],
       [10,  5,  2, 56, 45, 56]])

In [37]:
a[0, 3:5]

array([4, 5])

In [38]:
a[:,2]

array([3, 8, 6, 1, 4, 2])

In [39]:
a[2::2]

array([[5, 4, 6, 8, 7, 5],
       [4, 2, 4, 6, 5, 7]])

In [40]:
a[2::2,::2]


array([[5, 6, 7],
       [4, 4, 5]])

In [41]:
a[2:3]

array([[5, 4, 6, 8, 7, 5]])

## Slices are refrence:
##### slices are refrences to location in memory,these memory locations can be used in assignment operations.

In [42]:
a=np.array([0,4,8,9,5])
a

array([0, 4, 8, 9, 5])

In [43]:
a[-2:]

array([9, 5])

In [44]:
a[-2:]=[4,6]
a

array([0, 4, 8, 4, 6])

In [45]:
a[-2:]=99

In [46]:
a

array([ 0,  4,  8, 99, 99])

In [47]:
a=np.arange(25).reshape(5,5)

In [48]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
a[-1:]

array([[20, 21, 22, 23, 24]])

In [50]:
a[2::2,::2]

array([[10, 12, 14],
       [20, 22, 24]])

# Sliced array share data

In [51]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [52]:
b=a[2:4]
b

array([3, 4])

In [53]:
b[0]=10

In [54]:
a

array([ 1,  2, 10,  4,  5,  6])

# Fancy Indexing:

### Indexing by position:

In [55]:
a=np.arange(0,80,10)

In [56]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [57]:
indices=[1,2,-3]
y=a[indices]
y

array([10, 20, 50])

In [58]:
a[indices]=99
a

array([ 0, 99, 99, 30, 40, 99, 60, 70])

### indexing with booleans:

In [59]:
mask=np.array([0,1,0,1,0,0,4,8],dtype=bool)
mask

array([False,  True, False,  True, False, False,  True,  True])

In [60]:
y=a[mask]
y

array([99, 30, 60, 70])

## Fancy indexing in 2-D

In [61]:
a=np.arange(25).reshape(5,5)

In [62]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
a[3:, [0,2,4]]

array([[15, 17, 19],
       [20, 22, 24]])

In [64]:
mask=np.array([0,1,1,0,1],dtype=bool)

In [65]:
a[mask,2]

array([ 7, 12, 22])

# Numpy Creating Arrays:

### array constructor:

In [66]:
a=np.array([0,1.,2,3])

In [67]:
a.nbytes

32

In [68]:
a.dtype

dtype('float64')

In [69]:
#reducing precision
a=np.array([0,1.,2,3],dtype='float32')
a

array([0., 1., 2., 3.], dtype=float32)

In [70]:
a.shape

(4,)

In [71]:
a.ndim

1

In [72]:
a.dtype

dtype('float32')

In [73]:
a.nbytes

16

# Array Creation Functions:

In [74]:
#arange([start,],stop[,step],dtype=None)
a=np.arange(4)
a

array([0, 1, 2, 3])

In [75]:
a=np.arange(0,2*np.pi,np.pi/4)

In [76]:
b=np.sin(a)
b

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01])

In [77]:
np.ones((2,3),dtype='float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [78]:
np.zeros((2,3),dtype='float32')

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [79]:
a=np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [80]:
np.empty(2)

array([5.43230922e-312, 7.29112202e-304])

In [81]:
np.full(3,5.0)

array([5., 5., 5.])

In [82]:
a.fill(4)
a

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [83]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [84]:
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [85]:
a=np.array([[15,2,31],[4,15,6]])
a

array([[15,  2, 31],
       [ 4, 15,  6]])

In [86]:
a.sum()

73

In [87]:
a.sum(axis=0)

array([19, 17, 37])

In [88]:
a.sum(axis=1)

array([48, 25])

In [89]:
a.sum(axis=-1)

array([48, 25])

### min(),max(),argmax(),argmin(used for finding minimum element location):

In [90]:
a.argmax()

2

In [91]:
a.argmin()

1

## Where

In [92]:
a=np.arange(-2,2)**2

In [93]:
a

array([4, 1, 0, 1], dtype=int32)

In [94]:
mask=a%2==0

In [95]:
mask

array([ True, False,  True, False])

In [96]:
np.where(mask)

(array([0, 2], dtype=int64),)

In [97]:
a.std()

1.5

In [98]:
a.var()

2.25

In [99]:
a.mean()

1.5

## Broadcasting

In [100]:
a=np.array([10,20,30,40])
b=np.array([0,1,2])
y=a[:, np.newaxis]+b
y

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

## Broadcasting Indices:

In [102]:
data_cube=np.arange(27).reshape(3,3,3)
data_cube

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
yi,xi=np.meshgrid(np.arange(3),np.arange(3),sparse=True)
yi,xi

(array([[0, 1, 2]]), array([[0],
        [1],
        [2]]))

In [104]:
zi=np.array([[0,1,2],
            [1,1,2],
            [2,1,2]])
zi

array([[0, 1, 2],
       [1, 1, 2],
       [2, 1, 2]])

In [106]:
horizon=data_cube[xi,yi,zi]
horizon

array([[ 0,  4,  8],
       [10, 13, 17],
       [20, 22, 26]])

# Universal Function Methods:

In [107]:
#op.reduce()
a=np.array([1,2,3,4])

In [108]:
np.add.reduce(a)

10

In [111]:
a=np.array(['ab','cd','ef'],dtype='object')

In [112]:
np.add.reduce(a)

'abcdef'

#### logical operation :

In [113]:
a=np.array([0,1,1,0])

In [114]:
np.logical_and.reduce(a)

False

In [115]:
np.logical_or.reduce(a)

True

In [117]:
np.logical_xor.reduce(a)

False

In [118]:
a=np.arange(3)+np.arange(0,40,10).reshape(-1,1)
a

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [125]:
np.add.reduce(a,1)

array([ 3, 33, 63, 93])

In [128]:
#op.accumlate()
a=np.array([1,2,3,4])
np.add.accumulate(a)

array([ 1,  3,  6, 10], dtype=int32)

In [129]:
a=np.array(['ab','cd','ef'],dtype='object')
np.add.accumulate(a)

array(['ab', 'abcd', 'abcdef'], dtype=object)

In [133]:
#op.reduceat(a,axis)
a=np.array([0,10,20,30,40,50,60])
indices=np.array([1,5])
np.add.reduceat(a,indices)

array([100, 110], dtype=int32)

# Array DataStructure:

In [142]:
#a.flatten():change the multi-dimensinoal array into a 1-d array but reference array is the copy of original array
#a.ravel():same as flatten except that it changes the original array
a=np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [137]:
b=a.flatten()
b

array([0, 1, 2, 3, 4, 5])

In [140]:
b[0]=10
b

array([10,  1,  2,  3,  4,  5])

In [141]:
a

array([[10,  1,  2],
       [ 3,  4,  5]])

In [143]:
b=a.ravel()
b

array([0, 1, 2, 3, 4, 5])

In [144]:
b[0]=10
b

array([10,  1,  2,  3,  4,  5])

In [145]:
a

array([[10,  1,  2],
       [ 3,  4,  5]])

# Thanks.